name: Test Vue App
on: workflow_dispatch
jobs:
  runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
        # with: .......
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run lint
        
      
      
      
    
